name: Tests

on:
  push:
    branches: [dev, main]
    paths-ignore:
      - '**.md'
      - '.github/workflows/**'
  pull_request:
    branches: [dev, main]

permissions:
  contents: read

concurrency:
  group: tests-${{ github.ref }}
  cancel-in-progress: true

jobs:
  format:
    name: Format / Vet
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          check-latest: true
        env:
          GOTOOLCHAIN: auto

      - name: Go env
        run: |
          go version
          go env

      - name: Verify formatting (gofmt)
        run: |
          UNFORMATTED=$(gofmt -s -l . | tee /dev/stderr)
          if [ -n "$UNFORMATTED" ]; then
            echo "The files above are not gofmt-formatted. Run 'go fmt ./...' locally." >&2
            exit 1
          fi

      - name: Go vet
        run: go vet ./...

  test:
    runs-on: ubuntu-latest
    needs: [format]
    if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}
    env:
      DOCKER_BUILDKIT: 1
      COMPOSE_DOCKER_CLI_BUILD: 1

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Show Docker/Compose versions
        run: |
          docker --version
          docker compose version

      - name: Run tests (Makefile)
        run: make tests
        timeout-minutes: 20
